psql_helper in classification_element
Kitware/SMQTK-Classifier pull request #11
Opened 2021-07-19 17:45 UTC by bardkw

2021-07-19 18:46 UTC, Purg requested changes

2021-07-19 18:46 UTC, Purg commented on smqtk_classifier/impls/classification_element/postgres.py
> +        conn = self._psql_helper.get_psql_connection()
Here we want to replace most of body with the use of the `self._psql_helper.single_execute` method. See the `get_bytes` method in `smqtk_dataprovider/impls/data_element/psql.py` for example.

2021-07-29 18:42 UTC, bardkw commented
Altered `get_classification` and `set_classification` to use `single_execute`. The only thing I am unsure about is wether the `ensure_table` function is needed in the callback function.

2021-08-03 19:04 UTC, Purg commented
> Altered `get_classification` and `set_classification` to use `single_execute`. The only thing I am unsure about is wether the `ensure_table` function is needed in the callback function.

You do not need to call it manually. As long as `set_table_upsert_sql` is called with a upsert statement string, `ensure_table` will be appropriately called in the `*_execute` methods. Apparently there is a separate issue that `set_table_upsert_sql` is not documented too well (or much at all) but the effect is that if you set an upsert statement string via the `set_table_upsert_sql` method, then it's invocation is set to happen automatically before execution operations.

2021-08-04 13:00 UTC, bardkw commented
removed the manual `ensure` calls

2021-08-04 18:19 UTC, merged